[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serce_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
colored = "2.0"
